export const IS_SHOWFONTLIST_MODAL_ACTION = "IS_SHOWFONTLIST_MODAL_ACTION";

export const LOAD_MENU_LIST = "LOAD_MENU_LIST";

export const TABLE_SELECT_CHANGE = "MENU_TABLE_SELECT_CHANGE";

export const TABLE_DEL_ITEM = "MENU_TABLE_DEL_ITEM";

export const CHANGE_FILTER_PARAM = "MENU_CHANGE_FILTER_PARAM";

export const RESET_LOAD_GRID = "MENU_RESET_LOAD_GRID ";

export const IS_SHOW_ADD_MENU_MODAL = "IS_SHOW_ADD_MENU_MODAL";

export const IS_SHOW_VIEW_MENU_MODAL = "IS_SHOW_VIEW_MENU_MODAL";

export const IS_SHOW_UPDATE_MENU_MODAL = "IS_SHOW_UPDATE_MENU_MODAL";

export const ADD_MENU_OPER = "ADD_MENU_OPER";

export const UPDATE_MENU_OPER = "UPDATE_MENU_OPER";

export const VIEW_MENU_OPER = "VIEW_MENU_OPER";

export const GET_DETAILBY_ID = "MENU_GET_DETAILBY_ID";







