export const LOAD_LOGLOGIN_LIST = "LOAD_LOGLOGIN_LIST";

export const TABLE_SELECT_CHANGE = "TABLE_SELECT_CHANGE";

export const TABLE_DEL_ITEM = "TABLE_DEL_ITEM";

export const CHANGE_FILTER_PARAM = "CHANGE_FILTER_PARAM";

export const RESET_LOAD_GRID = "RESET_LOAD_GRID ";
