export const LOAD_LOGOPERATE_LIST = "LOAD_LOGOPERATE_LIST";

export const TABLE_SELECT_CHANGE = "TABLE_LOGOPERATE_SELECT_CHANGE";

export const TABLE_DEL_ITEM = "TABLE_LOGOPERATE_DEL_ITEM";

export const CHANGE_FILTER_PARAM = "CHANGE_LOGOPERATE_FILTER_PARAM";

export const RESET_LOAD_GRID = "RESET_LOGOPERATE_LOAD_GRID ";



