export const LOAD_LOGERROR_LIST = "LOAD_LOGERROR_LIST";

export const TABLE_SELECT_CHANGE = "TABLE_LOGERROR_SELECT_CHANGE";

export const TABLE_DEL_ITEM = "TABLE_LOGERROR_DEL_ITEM";

export const CHANGE_FILTER_PARAM = "CHANGE_LOGERROR_FILTER_PARAM";

export const RESET_LOAD_GRID = "RESET_LOGERROR_LOAD_GRID ";






