export const LOAD_USER_LIST = "LOAD_USER_LIST";

export const TABLE_SELECT_CHANGE = "TABLE_SELECT_CHANGE";

export const TABLE_DEL_ITEM = "TABLE_DEL_ITEM";

export const CHANGE_FILTER_PARAM = "CHANGE_FILTER_PARAM";

export const RESET_LOAD_GRID = "RESET_LOAD_GRID ";

export const IS_SHOW_ADD_USER_MODAL = "IS_SHOW_ADD_USER_MODAL";

export const IS_SHOW_VIEW_USER_MODAL = "IS_SHOW_VIEW_USER_MODAL";

export const IS_SHOW_UPDATE_USER_MODAL = "IS_SHOW_UPDATE_USER_MODAL";

export const ADD_USER_OPER = "ADD_USER_OPER";

export const UPDATE_USER_OPER = "UPDATE_USER_OPER";

export const VIEW_USER_OPER = "VIEW_USER_OPER";


