export const LOAD_DICITEM_LIST = "LOAD_DICITEM_LIST";

export const TABLE_SELECT_CHANGE = "TABLE_DICITEM_SELECT_CHANGE";

export const TABLE_DEL_ITEM = "TABLE_DICITEM_DEL_ITEM";

export const CHANGE_FILTER_PARAM = "CHANGE_DICITEM_FILTER_PARAM";

export const RESET_LOAD_GRID = "RESET_DICITEM_LOAD_GRID ";

export const IS_SHOW_ADD_DICITEM_MODAL = "IS_SHOW_ADD_DICITEM_MODAL";

export const IS_SHOW_VIEW_DICITEM_MODAL = "IS_SHOW_VIEW_DICITEM_MODAL";

export const IS_SHOW_VIEW_DICITEM_ITEM_MODAL = "IS_SHOW_VIEW_DICITEM_ITEM_MODAL";

export const IS_SHOW_UPDATE_DICITEM_MODAL = "IS_SHOW_UPDATE_DICITEM_MODAL";

export const ADD_DICITEM_OPER = "ADD_DICITEM_OPER";

export const UPDATE_DICITEM_OPER = "UPDATE_DICITEM_OPER";

export const GET_DETAILBY_ID = "GET_DETAILBY_ID";


