export const LOAD_ROLE_LIST = "LOAD_ROLE_LIST";

export const TABLE_SELECT_CHANGE = "TABLE_ROLE_SELECT_CHANGE";

export const TABLE_DEL_ITEM = "TABLE_ROLE_DEL_ITEM";

export const CHANGE_FILTER_PARAM = "CHANGE_ROLE_FILTER_PARAM";

export const RESET_LOAD_GRID = "RESET_ROLE_LOAD_GRID ";

export const IS_SHOW_ADD_ROLE_MODAL = "IS_SHOW_ADD_ROLE_MODAL";

export const IS_SHOW_VIEW_ROLE_MODAL = "IS_SHOW_VIEW_ROLE_MODAL";

export const IS_SHOW_VIEW_ROLE_ITEM_MODAL = "IS_SHOW_VIEW_ROLE_ITEM_MODAL";

export const IS_SHOW_UPDATE_ROLE_MODAL = "IS_SHOW_UPDATE_ROLE_MODAL";

export const ADD_ROLE_OPER = "ADD_ROLE_OPER";

export const UPDATE_ROLE_OPER = "UPDATE_ROLE_OPER";

export const GET_DETAILBY_ID = "GET_ROLE_DETAILBY_ID";



