export const LOAD_USER_ROLE_LIST = "LOAD_USER_ROLE_LIST";

export const TABLE_SELECT_CHANGE = "TABLE_USER_ROLE_SELECT_CHANGE";

export const TABLE_DEL_ITEM = "TABLE_USER_ROLE_DEL_ITEM";

export const CHANGE_FILTER_PARAM = "CHANGE_USER_ROLE_FILTER_PARAM";

export const RESET_LOAD_GRID = "RESET_USER_ROLE_LOAD_GRID ";

export const IS_SHOW_ADD_USER_ROLE_MODAL = "IS_SHOW_ADD_USER_ROLE_MODAL";

export const IS_SHOW_VIEW_USER_ROLE_MODAL = "IS_SHOW_VIEW_USER_ROLE_MODAL";

export const IS_SHOW_VIEW_USER_ROLE_ITEM_MODAL = "IS_SHOW_VIEW_USER_ROLE_ITEM_MODAL";

export const IS_SHOW_UPDATE_USER_ROLE_MODAL = "IS_SHOW_UPDATE_USER_ROLE_MODAL";

export const ADD_USER_ROLE_OPER = "ADD_USER_ROLE_OPER";

export const UPDATE_USER_ROLE_OPER = "UPDATE_USER_ROLE_OPER";

export const GET_DETAILBY_ID = "GET_USER_ROLE_DETAILBY_ID";

export const IS_SHOW_MENUSETTING_MODAL = "IS_SHOW_MENUSETTING_MODAL";

export  const  SHOW_VIEWMENU_SETTING_MODAL= "SHOW_VIEWMENU_SETTING_MODAL";


