export const LOAD_LIVEROOMINFO_LIST = "LOAD_LIVEROOMINFO_LIST";

export const TABLE_SELECT_CHANGE = "TABLE_LIVEROOMINFO_SELECT_CHANGE";

export const TABLE_DEL_ITEM = "TABLE_LIVEROOMINFO_DEL_ITEM";

export const CHANGE_FILTER_PARAM = "CHANGE_LIVEROOMINFO_FILTER_PARAM";

export const RESET_LOAD_GRID = "RESET_LIVEROOMINFO_LOAD_GRID ";

export const IS_SHOW_ADD_LIVEROOMINFO_MODAL = "IS_SHOW_ADD_LIVEROOMINFO_MODAL";

export const IS_SHOW_VIEW_LIVEROOMINFO_MODAL = "IS_SHOW_VIEW_LIVEROOMINFO_MODAL";

export const IS_SHOW_UPDATE_LIVEROOMINFO_MODAL = "IS_SHOW_UPDATE_LIVEROOMINFO_MODAL";

export const ADD_LIVEROOMINFO_OPER = "ADD_LIVEROOMINFO_OPER";

export const UPDATE_LIVEROOMINFO_OPER = "UPDATE_LIVEROOMINFO_OPER";

export const VIEW_LIVEROOMINFO_OPER = "VIEW_LIVEROOMINFO_OPER";

export const GET_DETAILBY_ID = "GET_DETAILBY_LIVEROOMINFO_ID";
